export const products = [
    {
        'id' : 'p1',
        'name' : 'Colored Shawl',
        'price' : '1200',
        'description': '100% Pure cotton',
        'code': 'SKU : 29764 P (C-5)',
        'quantity': '5',
        'size': 'large',
        'image': '/images/img1.jpg',
        'inStock' : 'yes',
        'sale': 'no',
        'discount': '10%',
    },
    {
        'id' : 'p2',
        'name' : 'Russian Kerchief',
        'price' : '2200',
        'description': 'Warm cotton',
        'code': 'SKU : 29764 P (C-33)',
        'quantity': '2',
        'size': 'large',
        'image': '/images/img2.jpg',
        'inStock' : 'yes',
        'sale': 'no',
        'discount': '20%',
    },
    {
        'id' : 'p3',
        'name' : 'Handmade Woolen Stripe',
        'price' : '3500',
        'description': 'Pure Cotton',
        'code': 'SKU : 29734 P (C-5)',
        'quantity': '1',
        'size': 'large',
        'image': '/images/img3.jpg',
        'inStock' : 'yes',
        'sale': 'no',
        'discount': '10%',
    },
    {
        'id' : 'p4',
        'name' : 'Handmade Shawl',
        'price' : '500',
        'description': 'woolen shawl for winters',
        'code': 'SMF : 29764 P (C-5)',
        'quantity': '2',
        'size': 'medium',
        'image': '/images/img4.jpg',
        'inStock' : 'yes',
        'sale': 'yes',
        'discount': '10%',
    },
    {
        'id' : 'p5',
        'name' : 'Cashmere Silk Scarf',
        'price' : '2500',
        'description': 'silk stuff',
        'code': 'AJK : 29764 P (C-5)',
        'quantity': '2',
        'size': 'large',
        'image': '/images/img5.jpg',
        'inStock' : 'yes',
        'sale': 'no',
        'discount': '10%',
    },
    {
        'id' : 'p6',
        'name' : 'Kashmiri Shawl',
        'price' : '300',
        'description': 'Made up of pure cotton',
        'code': 'AMK : 29764 P (C-5)',
        'quantity': '3',
        'size': 'large',
        'image': '/images/img6.jpg',
        'inStock' : 'yes',
        'sale': 'no',
        'discount': '10%',
    },
    {
        'id' : 'p7',
        'name' : 'Woolen Handmade Shawl',
        'price' : '800',
        'description': 'Pure wool',
        'code': 'SKU : 29764 P (C-5)',
        'quantity': '5',
        'size': 'large',
        'image': '/images/img7.jpg',
        'inStock' : 'yes',
        'sale': 'no',
        'discount': '10%',
    },
    {
        'id' : 'p8',
        'name' : 'Oriental Rugs',
        'price' : '1500',
        'description': 'leather shoes',
        'code': 'SKU : 29764 P (C-5)',
        'quantity': '5',
        'size': 'large',
        'image': '/images/img8.jpg',
        'inStock' : 'yes',
        'sale': 'no',
        'discount': '10%',
    },
    
];